[package]
name = "waveformrs"
version = "0.1.0"
authors = ["Aziz Unsal <unsal.aziz@gmail.com>"]

[dependencies]
clap = "2.32.0"
hound = "3.1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
image = "*"
imageproc = "*"